name: ToDo
description: Flutter Hive Todo app

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.3.3
  intl: ^0.19.0
  flutter_datetime_picker: ^1.5.1
  animate_do: ^3.3.4
  flutter_beautiful_popup: ^1.7.0
  panara_dialogs: ^0.1.2
  lottie: ^3.1.0
  ftoast: ^2.0.0
  flutter_slider_drawer: ^2.1.1
  file: ^6.1.4
  flutter_datetime_picker_plus: ^2.1.0
  animated_splash_screen: ^1.3.0
  flutter_local_notifications: ^17.0.0
  rive: ^0.13.1
  timezone : ^0.9.0
  awesome_notifications: ^0.8.2
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.4
  share: ^2.0.4
  share_plus: ^8.0.2

flutter_icons:
  android: true
  image_path: "assets/img/ic_launcher.png"
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/lottie/
    - assets/Backgrounds/
    - assets/RiveAssets/
  

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
